# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p2VysFrv76CAG9XD7Gi8kL0zMyMHv_4R
"""

# FastAPI for MNIST CNN Model (PyTorch)

from fastapi import FastAPI, File, UploadFile, HTTPException
import torch
import torch.nn as nn
from PIL import Image
import torchvision.transforms as transforms
import io
from fastapi.middleware.cors import CORESMiddleware
app=FastAPI(title="MNIST CNN API")
# -------------------------------
# 1. Define Model (same as training)
# -------------------------------
app.add_middleware(CORSEMiddleware,allow_origins=["*"], allow_credentials=True, allow_methods=["*"], allow_headers=["*"],)


class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()

        self.conv_layers = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=3),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(32, 64, kernel_size=3),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )

        self.fc_layers = nn.Sequential(
            nn.Flatten(),
            nn.Linear(64 * 5 * 5, 128),
            nn.ReLU(),
            nn.Linear(128, 10)
        )

    def forward(self, x):
        x = self.conv_layers(x)
        x = self.fc_layers(x)
        return x

# -------------------------------
# 2. Load Model Weights
# -------------------------------
model = CNN()
model.load_state_dict(torch.load("mnist_cnn_weights.pth", map_location=torch.device('cpu')))
model.eval()

# -------------------------------
# 3. Initialize FastAPI
# -------------------------------
app = FastAPI(title="MNIST Digit Classifier API")

# -------------------------------
# 4. Image Preprocessing
# -------------------------------
transform = transforms.Compose([
    transforms.Grayscale(num_output_channels=1),
    transforms.Resize((28, 28)),
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

# -------------------------------
# 5. Home Route
# -------------------------------
@app.get("/")
def home():
    return {"message": "MNIST CNN API is running"}

# -------------------------------
# 6. Prediction Route
# -------------------------------
@app.post("/predict")
async def predict(file: UploadFile = File(...)):
    # Read image
    contents = await file.read()
    image = Image.open(io.BytesIO(contents))

    # Preprocess image
    image = transform(image).unsqueeze(0)

    # Prediction
    with torch.no_grad():
        outputs = model(image)
        _, predicted = torch.max(outputs, 1)

    return {"predicted_digit": int(predicted.item())}